### ISSUE TITLE
电脑的微软系 uwp app全部断网

### ISSUE THREAD

**Issue by Genion** [a86913179/clash-tap#1]
账号登不上 UWP应用OneNote不能同步 store不能下载东西 显示似乎没有连接到 internet

**Comment by a86913179** [comment]
> 账号登不上 UWP应用OneNote不能同步 store不能下载东西 显示似乎没有连接到 internet

把`config.yaml`的`fake-ip`改为`redir-host`即可

或者在`nameserver`后面添加`fake-ip-filter`：
```yaml
dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  nameserver:
    - 223.5.5.5
  fake-ip-filter:
    - 'dns.msftncsi.com'
    - 'www.msftncsi.com'
    - 'www.msftconnecttest.com'
```
